### PR TITLE
Prettier v3 support (v2)

### PR DESCRIPTION
**Pull request by tthornton3-chwy**
This is a fork off of https://github.com/electrovir/prettier-plugin-multiline-arrays/pull/27, that applies the diff provided by @richardsimko (thank you!), then fixes the tests / formatting etc.

This took a bit of debugging!

Worth noting-- I monkey patched `prettier-plugin-organize-imports`, because otherwise I would have had to re-write a bunch of javascript tests. I did it in an "okay" way, but we should probably no longer assume type declarations are allowed in plain js! Or maybe we could try adding the `@flow` annotation?? I tried for 2 seconds and it didn't immediately work, so I just did this haha.

### CODE REVIEW

**Comment by richardsimko** [comment]
Great! Thanks for picking it up and glad to hear my small contribution was useful :)

**Comment by electrovir** [comment]
Hey thanks for this @tthornton3-chwy! I'll try to take a look this weekend.

**Review by electrovir — APPROVED** [review]
Looks fantastic @tthornton3-chwy. Thank you so much! I've got some clean up to do before releasing but tests are passing locally which was the main issue.

**Comment by electrovir** [comment]
@richardsimko note that I added an empty commit to the `main` branch under your name to indicate your contribution of the `concat` doc fix patch from #27 (in this comment https://github.com/electrovir/prettier-plugin-multiline-arrays/pull/27#discussion_r1319867801): 

https://github.com/electrovir/prettier-plugin-multiline-arrays/commit/fc53db2a87c613e5b69a1184592dfff4cd35375a

(The commit is empty because the changes were already incorporated into @tthornton3-chwy's commit [`fded62c`](https://github.com/electrovir/prettier-plugin-multiline-arrays/pull/28/commits/fded62c033204d60c97de4c32f3091717c2af81d) but I didn't want to rebase this branch as it would nuke the "verified" status of their commits.)

**Comment by tthornton3-chwy** [comment]
Thanks again @electrovir for your amazing work on this plugin-- this is a huge thing for a lot of people that you've managed to help! Cheers!

**Pull request merged**
